In [1]:
import numpy as np
import cv2


 ## Blank  White frame

In [2]:
img = np.ones((511, 511, 3))
print(img)
cv2.imshow('frame', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 ...

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [5]:
# Creating black lines
#                  (coordinates), (B,G,R), Thickness  Each color can value between 0 and 255
img = cv2.line(img,(0,0),(511,511),(0,0,0),5)
img = cv2.line(img,(511,0),(0,511),(0,0,0),5)
cv2.imshow('frame',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


## Blank Black Frame

In [6]:
img = np.zeros((511,511, 3))
print(img)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


## Creating Red lines

In [7]:
img = cv2.line(img,(0,0),(511,511),(0,0,255),5)
img = cv2.line(img,(511,0),(0,511),(0,0,255),5)
cv2.imshow('frame',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Creating Rectangle

In [8]:
img_path = "C://Users//Swati//Python_Basics//sample_images//messi5.jpg"
img = cv2.imread(img_path,1)
img = cv2.rectangle(img,(150,150),(350,256),(0,0,255),2)
cv2.imshow('frame',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# imread(path, flag)
# path: A string representing the path of the image to be read.
# flag: It specifies the way in which image should be read. It’s default value is cv2.IMREAD_COLOR


In [9]:
#Creating Circle
img = np.zeros((512, 512, 3))
img_path = "C://Users//Swati//Python_Basics//sample_images//messi5.jpg"
img = cv2.imread(img_path,1)
#                     (center), radius, (B,G,R)
img = cv2.circle(img,(245,100),50,(0,255,255),3)
cv2.imshow('frame',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
# Creating polygon
img = np.zeros((512, 512, 3))
pts = np.array([[200, 200], [200, 100], [400, 100], [400,200], [300, 250]], np.int32)
img = cv2.polylines(img,[pts],True,(0,255,255))
cv2.imshow('frame',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
# Inserting Text
img_path = "C://Users//Swati//Python_Basics//sample_images//apple.jpg"
img = cv2.imread(img_path,1)
font = cv2.FONT_HERSHEY_SIMPLEX
#                 string,  coordinates, font, scale, (B,G,R), Line Thickness, Line Type
cv2.putText(img, 'Apple', (170,300), font, 2, (255,255,0), 1, cv2.LINE_AA)
cv2.imshow('frame', img)
cv2.waitKey(0)
cv2.destroyAllWindows()