In [1]:
import numpy as np
import pandas as pd

In [2]:
data = np.random.rand(25).reshape(5,5)

In [3]:
print(data)

[[0.3400888  0.50109415 0.03190046 0.83347876 0.85108022]
 [0.55681226 0.03008579 0.24955729 0.40910055 0.84505575]
 [0.13000085 0.79090847 0.79002706 0.67832891 0.07483686]
 [0.5283043  0.60667756 0.16090671 0.25413648 0.66444616]
 [0.63875442 0.13732836 0.07081485 0.39167559 0.9066543 ]]


In [7]:
frame = pd.DataFrame(data, index = "R1 R2 R3 R4 R5".split(),columns = "C1 C2 C3 C4 C5".split())

In [8]:
print(frame)

          C1        C2        C3        C4        C5
R1  0.340089  0.501094  0.031900  0.833479  0.851080
R2  0.556812  0.030086  0.249557  0.409101  0.845056
R3  0.130001  0.790908  0.790027  0.678329  0.074837
R4  0.528304  0.606678  0.160907  0.254136  0.664446
R5  0.638754  0.137328  0.070815  0.391676  0.906654


In [9]:
frame1 = frame[frame> 0.2]

In [10]:
print(frame1)

          C1        C2        C3        C4        C5
R1  0.340089  0.501094       NaN  0.833479  0.851080
R2  0.556812       NaN  0.249557  0.409101  0.845056
R3       NaN  0.790908  0.790027  0.678329       NaN
R4  0.528304  0.606678       NaN  0.254136  0.664446
R5  0.638754       NaN       NaN  0.391676  0.906654


## Drop missing data 

In [13]:
frame1.dropna()  #drops all rows containing Nans

Empty DataFrame
Columns: [C1, C2, C3, C4, C5]
Index: []

In [14]:
frame1.dropna(axis = 1)

C4
R1  0.833479
R2  0.409101
R3  0.678329
R4  0.254136
R5  0.391676

In [18]:
frame1.dropna(thresh = 4)  #dropping rows which have less than 4 valid data points

C1        C2        C3        C4        C5
R1  0.340089  0.501094       NaN  0.833479  0.851080
R2  0.556812       NaN  0.249557  0.409101  0.845056
R4  0.528304  0.606678       NaN  0.254136  0.664446

In [19]:
frame1.dropna(axis = 1,thresh = 4)  #dropping columns with less than 4 valid points

C1        C4        C5
R1  0.340089  0.833479  0.851080
R2  0.556812  0.409101  0.845056
R3       NaN  0.678329       NaN
R4  0.528304  0.254136  0.664446
R5  0.638754  0.391676  0.906654

## Fill missing data

In [20]:
frame1.fillna(value = 99)

C1         C2         C3        C4         C5
R1   0.340089   0.501094  99.000000  0.833479   0.851080
R2   0.556812  99.000000   0.249557  0.409101   0.845056
R3  99.000000   0.790908   0.790027  0.678329  99.000000
R4   0.528304   0.606678  99.000000  0.254136   0.664446
R5   0.638754  99.000000  99.000000  0.391676   0.906654

In [22]:
frame1.loc["R2"].fillna(value = 45)

C1     0.556812
C2    45.000000
C3     0.249557
C4     0.409101
C5     0.845056
Name: R2, dtype: float64

In [23]:
frame1["C3"].fillna(value = 89)

R1    89.000000
R2     0.249557
R3     0.790027
R4    89.000000
R5    89.000000
Name: C3, dtype: float64

In [ ]:
frame1["C3"] = [1,2,1,np.NaN, 2]
frame1["C3"].fillna(value = frame1["".mean())