# Indexing and Slicing

In [1]:
import numpy as np
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [2]:
print(arr[2])   #print value at a given index

2


In [4]:
print(arr[1:6])

[1 2 3 4 5]


In [5]:
print(arr[:5])

[0 1 2 3 4]


In [6]:
print(arr[2:6:2])

[2 4]


In [8]:
arr[2:6] = 201          #set the specified range elements to a particular value
print(arr)

[  0   1 201 201 201 201   6   7   8   9  10]


In [9]:
mul_arr = np.arange(15).reshape(5,3)
print(mul_arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [12]:
print(mul_arr[2:3])         #print 2nd row and  

[[6 7 8]]


In [14]:
print(mul_arr[3,2])       #print element from 3(4th) row and col 2(3rd)  

11


In [16]:
print(mul_arr[2:4, 1])         #print 2nd column(1) for 2nd row through 4th row(4th row excluded)

[ 7 10]


# Boolean Indexing

In [17]:
import numpy as np
arr1 = np.arange(0,7)
print(arr1)

[0 1 2 3 4 5 6]


In [19]:
mod = [True, False, True, True, False, True, False]
print(arr1[mod])         #prints elements with indexes true

[0 2 3 5]


In [21]:
limit = 4
above_limit = arr1>limit
print(above_limit)

[False False False False False  True  True]


In [23]:
print(arr1[above_limit])     #prints list of elements above limit

[5 6]


In [25]:
a = np.arange(10).reshape(5,2)
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [27]:
b1 = np.array([True, False,True, False, True]) #prints the rows in a for which b1 holds true
print(a[b1])

[[0 1]
 [4 5]
 [8 9]]


# Copy

No copy, Shallow copy, Deep copy


## No copy

In [28]:
print(arr)

[  0   1 201 201 201 201   6   7   8   9  10]


In [32]:
new_arr = arr
print(new_arr)
print(new_arr is arr)   #checks if both are same object

[  0   1  29  29 201 201   6   7   8   9  10]
True


In [30]:
new_arr[2:4] = 29    #modifying content for new_arr
print(new_arr)

[  0   1  29  29 201 201   6   7   8   9  10]


In [31]:
print(arr)    #note that the content for arr has also changed

[  0   1  29  29 201 201   6   7   8   9  10]


## Deep copy

In [33]:
arr = np.arange(9)

In [34]:
print(arr)
new_arr = arr.copy()
print(new_arr)
print(new_arr is arr)

[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]
False


In [35]:
new_arr[2:5] = 78
print(new_arr)
print(arr)       #new_arr and arr are not same

[ 0  1 78 78 78  5  6  7  8]
[0 1 2 3 4 5 6 7 8]


In [4]:
import numpy as np
s = np.random.standard_normal(100)
s

array([ 0.86337824, -0.23513645,  0.48087106, -1.41549279, -0.74028368,
        0.04689656, -0.81776543, -0.00639514, -0.66324603, -0.20814301,
        0.43511904, -1.54741579, -1.28275783, -1.18692996,  0.5624093 ,
       -1.35435586, -0.68218707, -1.27695806, -0.64313382,  1.023663  ,
       -0.79067382, -0.36865854, -1.29330327,  0.4915024 ,  1.45355967,
        0.39576479,  1.2182946 , -0.64042714, -0.07100987, -0.5637136 ,
       -1.75108076, -1.0372571 , -0.03495359, -1.00401114, -2.3556887 ,
       -1.29891057,  0.53169682, -0.11302582, -0.65065333, -1.09967842,
        0.07669084,  0.60946606, -0.91542346,  1.13245398, -0.49144369,
        0.07930359,  0.24765793,  0.39505176, -0.10326875, -2.73021089,
        1.06404315, -0.44874644, -0.60783266,  0.62028091,  1.72655723,
        1.33452052, -0.7656118 ,  0.54489867,  1.77618242, -1.88322068,
        1.07395473,  0.03601307, -0.15887241, -0.233196  ,  0.55339519,
       -1.36604983, -1.90264236,  0.99655241,  0.38570836,  1.04

In [16]:
import numpy as np
array1 = np.random.randint(28)
array1

8

In [25]:
import numpy as np
arr =  np.random.randint(0,20,32).reshape(2,2,2,4)
print(arr.ndim)


4


In [26]:
x = np.linspace(10,20,100)
print(x)

[10.         10.1010101  10.2020202  10.3030303  10.4040404  10.50505051
 10.60606061 10.70707071 10.80808081 10.90909091 11.01010101 11.11111111
 11.21212121 11.31313131 11.41414141 11.51515152 11.61616162 11.71717172
 11.81818182 11.91919192 12.02020202 12.12121212 12.22222222 12.32323232
 12.42424242 12.52525253 12.62626263 12.72727273 12.82828283 12.92929293
 13.03030303 13.13131313 13.23232323 13.33333333 13.43434343 13.53535354
 13.63636364 13.73737374 13.83838384 13.93939394 14.04040404 14.14141414
 14.24242424 14.34343434 14.44444444 14.54545455 14.64646465 14.74747475
 14.84848485 14.94949495 15.05050505 15.15151515 15.25252525 15.35353535
 15.45454545 15.55555556 15.65656566 15.75757576 15.85858586 15.95959596
 16.06060606 16.16161616 16.26262626 16.36363636 16.46464646 16.56565657
 16.66666667 16.76767677 16.86868687 16.96969697 17.07070707 17.17171717
 17.27272727 17.37373737 17.47474747 17.57575758 17.67676768 17.77777778
 17.87878788 17.97979798 18.08080808 18.18181818 18

In [34]:
import numpy as np
arr =  np.random.randint(0,20,25).reshape(5,5)
print(arr)

print(arr[:,0:2])


[[ 2  0 16  9 17]
 [17 17 10  5  2]
 [13 16  5  4 17]
 [17  3 15  8  6]
 [ 8 18  1 12  6]]
[[ 2  0]
 [17 17]
 [13 16]
 [17  3]
 [ 8 18]]


In [41]:
arr = np.random.randint(10,20, 25)
print(arr)
print(arr.sum())
print(arr.max())
print(arr.min())

[14 19 18 18 13 19 19 16 12 19 14 14 11 10 13 14 12 14 18 11 14 12 14 14
 16]
368
19
10


In [43]:
arr = np.random.randint(10,20, 25)
print(arr)
Idx = [1,3,4]
arr[Idx]
# array(['a', 'd', 'h'], 
#       dtype='|S1')

[11 17 10 14 17 11 10 10 11 17 17 10 19 15 15 13 10 13 17 13 15 11 18 11
 17]


array([17, 14, 17])

In [56]:
import pandas as pd
data = pd.read_csv("car_sales.csv")
data.sort_values("Price")

Unnamed: 0   Manufacturer     Model     Type  Min.Price  Price  Max.Price  \
30          31           Ford   Festiva    Small        6.9    7.4        7.9   
43          44        Hyundai     Excel    Small        6.8    8.0        9.2   
52          53          Mazda       323    Small        7.4    8.3        9.1   
38          39            Geo     Metro    Small        6.7    8.4       10.0   
79          80         Subaru     Justy    Small        7.3    8.4        9.5   
..         ...            ...       ...      ...        ...    ...        ...   
3            4           Audi       100  Midsize       30.8   37.7       44.6   
18          19      Chevrolet  Corvette   Sporty       34.6   38.0       41.5   
10          11       Cadillac   Seville  Midsize       37.5   40.1       42.7   
47          48       Infiniti       Q45  Midsize       45.4   47.9       50.4   
58          59  Mercedes-Benz      300E  Midsize       43.8   61.9       80.0   

    MPG.city  MPG.highway             AirBags  ... Passengers Length  \
30        31           33                None  ...          4    141   
43        29           33                None  ...          5    168   
52        29           37                None  ...          4    164   
38        46           50                None  ...          4    151   
79        33           37                None  ...          4    146   
..       ...          ...                 ...  ...        ...    ...   
3         19           26  Driver & Passenger  ...          6    193   
18        17           25         Driver only  ...          2    179   
10        16           25  Driver & Passenger  ...          5    204   
47        17           22         Driver only  ...          5    200   
58        19           25  Driver & Passenger  ...          5    187   

    Wheelbase  Width  Turn.circle  Rear.seat.room Luggage.room  Weight  \
30         90     63           33            26.0         12.0    1845   
43         94     63           35            26.0         11.0    2345   
52         97     66           34            27.0         16.0    2325   
38         93     63           34            27.5         10.0    1695   
79         90     60           32            23.5         10.0    2045   
..        ...    ...          ...             ...          ...     ...   
3         106     70           37            31.0         17.0    3405   
18         96     74           43             NaN          NaN    3380   
10        111     74           44            31.0         14.0    3935   
47        113     72           42            29.0         15.0    4000   
58        110     69           37            27.0         15.0    3525   

     Origin                Make  
30      USA        Ford Festiva  
43  non-USA       Hyundai Excel  
52  non-USA           Mazda 323  
38  non-USA           Geo Metro  
79  non-USA        Subaru Justy  
..      ...                 ...  
3   non-USA            Audi 100  
18      USA  Chevrolet Corvette  
10      USA    Cadillac Seville  
47  non-USA        Infiniti Q45  
58  non-USA  Mercedes-Benz 300E  

[93 rows x 28 columns]

In [75]:
import pandas as pd
data = pd.read_csv("car_sales.csv")
print(data["Manufacturer"].nunique())

32


In [77]:
print(data["Wheelbase"].max())

119


In [78]:
car_Manufacturers = df.groupby('Manufacturer')
priceDf = car_Manufacturers['Manufacturer','Wheelbase'].max()
print(priceDf.max())

Manufacturer    Volvo
Wheelbase         119
dtype: object


<ipython-input-78-b94e0efefdaa>:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  priceDf = car_Manufacturers['Manufacturer','Wheelbase'].max()


In [93]:
car_Manufacturers = data.groupby('Manufacturer')
df = car_Manufacturers['Manufacturer','Passengers'].max()
print(df.max())

volvoDf = car_Manufacturers.get_group('Volvo')
print(volvoDf)



Manufacturer    Volvo
Passengers          8
dtype: object
    Unnamed: 0 Manufacturer Model     Type  Min.Price  Price  Max.Price  \
91          92        Volvo   240  Compact       21.8   22.7       23.5   
92          93        Volvo   850  Midsize       24.8   26.7       28.5   

    MPG.city  MPG.highway             AirBags  ... Passengers Length  \
91        21           28         Driver only  ...          5    190   
92        20           28  Driver & Passenger  ...          5    184   

    Wheelbase  Width  Turn.circle  Rear.seat.room Luggage.room  Weight  \
91        104     67           37            29.5         14.0    2985   
92        105     69           38            30.0         15.0    3245   

     Origin       Make  
91  non-USA  Volvo 240  
92  non-USA  Volvo 850  

[2 rows x 28 columns]


<ipython-input-93-3cdb2754de6a>:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df = car_Manufacturers['Manufacturer','Passengers'].max()
