# Arithmetic 

In [9]:
import numpy as np
arr =  np.random.randint(0,20,5)
print(arr)


[ 5  4 14  8  9]


In [10]:
arr = arr+arr
print(arr)

[10  8 28 16 18]


In [11]:
print(arr * arr)

[100  64 784 256 324]


In [12]:
print(arr**2)

[100  64 784 256 324]


In [13]:
print(arr/arr)

[1. 1. 1. 1. 1.]


In [14]:
print(arr< 30)       #compare the array values with 30 and prints result in boolean values

[ True  True  True  True  True]


# Matrix Operation

In [15]:
A = np.array([[1,0],[1,1]])
B = np.array([[2,3],[5,1]])

In [16]:
print(A*B)      #elementwise product

[[2 0]
 [5 1]]


In [17]:
print(A@B)         #matrix product

[[2 3]
 [7 4]]


# Universal Array Functions

In [18]:
print(np.sqrt(arr))

[3.16227766 2.82842712 5.29150262 4.         4.24264069]


In [19]:
print(np.exp(arr))

[2.20264658e+04 2.98095799e+03 1.44625706e+12 8.88611052e+06
 6.56599691e+07]


In [20]:
new_arr = np.random.randint(9,32,5)

In [21]:
print(np.add(arr,new_arr))

[37 31 37 39 35]


In [23]:
print(np.sin(arr))

[-0.54402111  0.98935825  0.27090579 -0.28790332 -0.75098725]


In [24]:
print(np.log(arr))

[2.30258509 2.07944154 3.33220451 2.77258872 2.89037176]
