# NumPy

In [2]:
import numpy as np
list1 = [2,7,8, 4,3 ,0,11,9,78,45, 6]
array1 = np.array(list1)
print(array1)

[ 2  7  8  4  3  0 11  9 78 45  6]


In [3]:
import numpy as np
list_of_list = [[1,2,3],[4,5,6],[7,8,9]]
array2 = np.array(list_of_list)
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
row_vector = np.array([1,2,3])
print(row_vector)

[1 2 3]


In [6]:
column_vector = np.array([[1],[2],[3]])
print(column_vector)

[[1]
 [2]
 [3]]


In [4]:
array1 = (np.arange(0,5))
print(array1)
print(type(array1))

[0 1 2 3 4]
<class 'numpy.ndarray'>


## arange

In [10]:
array1 = np.arange(0,20)
print(array1)
print(type(array1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>


In [11]:
array1 = np.arange(0,20,3)
print(array1)

[ 0  3  6  9 12 15 18]


In [12]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [16]:
print(np.ones((4,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
print(np.zeros((4,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Fill

In [3]:
filled_array = np.full((4,4), 7)           #fills 4x4 array with value 7
print(filled_array)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


## linspace

In [5]:
print(np.linspace(0,20,5))   #stop value is also considered in this case
#start, stop, step value are mentioned

[ 0.  5. 10. 15. 20.]


## eye

In [8]:
print(np.eye(9))          #prints an identity matrix

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [9]:
print(np.eye(9,k = 1))   #sets the diagonal offset by 1

[[0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## random

### rand

In [10]:
print(np.random.rand(5))

[0.01994301 0.67939701 0.98196632 0.03873447 0.47061187]


In [11]:
print(np.random.rand(5, 4))

[[0.29412065 0.12399044 0.29333954 0.58703143]
 [0.83063403 0.00929754 0.59402764 0.24222652]
 [0.72458943 0.10367566 0.35415791 0.32582407]
 [0.90376084 0.01922191 0.54584119 0.39426707]
 [0.62736611 0.90754764 0.20780701 0.74844406]]


### randn

In [12]:
print(np.random.randn(5))

[-0.41852383  0.1312722  -0.68548697  0.59926675 -0.2997983 ]


In [13]:
print(np.random.randn(5, 4))

[[-1.03582258  0.18164515  0.32671069 -0.00838525]
 [-0.02740261  0.7233207  -0.30992929 -0.6159328 ]
 [-0.59728509 -1.07222663 -0.26987911 -0.40113113]
 [ 0.04872213 -0.06031894  1.69928607 -0.32647597]
 [-0.43969654 -0.53336228  2.41348852 -0.69803584]]


### randint

In [14]:
print(np.random.randint(4, size = 5))      #prints an array of size 5 b/w 0 and 4 (4 is excluded)

[2 3 0 2 0]


In [15]:
print(np.random.randint(1,4, size = 5))

[3 1 3 1 1]


In [16]:
print(np.random.randint(1,4, size = (5,5)))

[[2 1 1 1 3]
 [1 1 3 1 1]
 [1 2 3 3 1]
 [2 1 1 2 3]
 [1 1 1 1 3]]


# Attributes of ndArray

In [18]:
sample_arrays = np.arange(20)
print(sample_arrays)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [20]:
sample_array_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(sample_array_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
print(sample_arrays.shape)

(20,)


In [22]:
print(sample_array_2.shape)

(3, 3)


In [23]:
print(sample_arrays.size)

20


In [24]:
print(sample_array_2.size)

9


### ndim

In [25]:
print(sample_arrays.ndim)

1


In [26]:
print(sample_array_2.ndim)

2


# Methods to change shape of an array

## reshape

In [29]:
print(sample_arrays.reshape(4,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [32]:
print(sample_arrays.reshape(2,10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


## ravel

In [34]:
print(sample_array_2.ravel())

[1 2 3 4 5 6 7 8 9]


In [35]:
print(sample_array_2.T)       #returns transpose 

[[1 4 7]
 [2 5 8]
 [3 6 9]]


## max, min, argmax, argmin

In [38]:
rand_array = np.random.randint(0,20,3) 
print(rand_array)

[ 2 18  2]


In [39]:
print(rand_array.max())

18


In [40]:
print(rand_array.argmax())

1


In [41]:
print(rand_array.min())

2


In [42]:
print(rand_array.argmin())

0


In [43]:
print(rand_array.sum())

22
