## Face and Eyes detecction using haar cascade

In [2]:
import cv2
import numpy as np
import time


In [3]:
cv2.__file__

'C:\\Users\\Swati\\anaconda3\\lib\\site-packages\\cv2\\__init__.py'

### Initiating Classifiers

In [4]:
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('haarcascade_eye.xml')

## Reading image

In [5]:
img = cv2.imread('federer.jpg')
print(img.shape)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow("Original", img)
cv2.imshow("Grayscale",gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

(320, 320, 3)


## Detecting face

In [6]:
faces = face_cascade.detectMultiScale(gray, scaleFactor = 1.3, minNeighbors = 5)
print(faces)

[[ 72  51 184 184]]


## Enclosing Face with rectangle

In [8]:
x, y, h, w = faces[0]
img = cv2.rectangle(img, (x,y), (x+ w, y+h), (0,0,255), 2)
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Creating ROI of face

In [9]:
roi_gray = gray[y:y+h, x:x+w]
roi_color = img[y:y+h, x:x+w]
cv2.imshow('ROI Gray (Face)', roi_gray)
cv2.imshow('ROI color (Face)', roi_color)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Detecting Eyes and Enclosing them with rectangles

In [10]:
eyes = eye_cascade.detectMultiScale(roi_gray)
print(eyes)

[[37 45 55 55]
 [95 48 50 50]]


In [11]:
for (ex, ey, ew, eh) in eyes:
    cv2.rectangle(roi_color, (ex, ey), (ex+ew, ey+eh), (0,255, 255), 2)
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Multiple faces in one image

In [12]:
img = cv2.imread('faces.jpeg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow("Original", img)
cv2.imshow("Gray image", gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:

# FACE DETECTION

In [1]:
import cv2
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline



In [2]:
def face_det(cascade, image,scaleFactor = 1.5):
    image_copy = image.copy()
#     converting in gray image
    gray_img = cv2.cvtColor(image_copy, cv2.COLOR_BGR2GRAY)
#     using haar classifier
    faces_detect = cascade.detectMultiScale(gray_img, scaleFactor = 1.5, minNeighbors = 2)
    for(x,y,w,h) in faces_detect:
        cv2.rectangle(image, (x,y), (x+w, y+h), (0,255,0), 5)
    return image_copy

# Loading image
image = cv2.imread("faces.jpeg")
# converting to grayscale
image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
# displaying gray image
cv2.imshow("Gray image",image_gray)
faces = face_det(haar_face_cascade, image)
cv2.imshow("Faces",faces)